# Generated by Django 5.2.4 on 2025-07-02 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='source',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(default='General Service', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='slot_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
